import { StyleSheet } from "react-native";
import { theme } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    paddingRight: 30,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.darkLight,
    backgroundColor: "white",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },

  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: theme.colors.textDark,
    flex: 1,
  },
  filterWrapper: {
    flex: 1,
    maxWidth: 150,
  },
  headerPicker: {
    height: 30,
    backgroundColor: "transparent",
    marginLeft: -8,
  },
  addButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
  },
  backButton: {
    marginRight: 16,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: theme.colors.textDark,
    marginTop: 2,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.colors.darkLight,
    borderRadius: 20,
    padding: 12,
    fontSize: 16,
    minHeight: 45,
    width: "70%",
  },
  saveButton: {
    flex: 1,
  },
  statusContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  statusButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.darkLight,
    backgroundColor: "white",
  },
  statusButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.textDark,
    marginLeft: 4,
  },
  statusTextActive: {
    color: "white",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
    width: "100%",
  },
  labelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    width: "30%",
    flexShrink: 0,
  },
  inputLabel: {
    fontSize: 14,
    color: theme.colors.textLight,
    flexShrink: 1,
    marginTop: 2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  statusLabel: {
    fontSize: 14,
    color: theme.colors.textLight,
    marginBottom: 6,
  },
  dateTimeContainer: {
    marginBottom: 16,
    width: "100%",
  },
  dateTimeLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  dateTimeInputs: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  dateTimeButton: {
    borderWidth: 1,
    borderColor: theme.colors.darkLight,
    borderRadius: 20,
    padding: 12,
    minHeight: 45,
    alignItems: "center",
    justifyContent: "center",
  },
  dateTimeText: {
    fontSize: 16,
    color: theme.colors.textDark,
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 2,
    marginBottom: 30,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "white",
  },
  bookingCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  bookingText: {
    fontSize: 14,
    color: theme.colors.textDark,
    marginBottom: 8,
  },
  editButton: {
    backgroundColor: theme.colors.primary,
    marginTop: 10,
  },
  editButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "500",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  dateText: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.textDark,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
  },
  routeContainer: {
    marginBottom: 8,
  },
  locationText: {
    fontSize: 15,
    color: theme.colors.textDark,
    fontWeight: "500",
  },
  returnTypeText: {
    fontSize: 12,
    color: theme.colors.textLight,
    marginTop: 4,
  },
  customerInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  nameText: {
    fontSize: 14,
    color: theme.colors.textDark,
  },
  phoneText: {
    fontSize: 14,
    color: theme.colors.textLight,
  },
  paymentInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  moneyText: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.textDark,
  },
  paymentStatus: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.textDark,
    backgroundColor: theme.colors.status.pending,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: theme.radius.sm,
  },
  driverInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  driverText: {
    fontSize: 14,
    color: theme.colors.textLight,
  },
  bookingStatus: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.textDark,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: theme.radius.sm,
  },
  filtersCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 8,
    borderRadius: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    zIndex: 3000,
  },
  filterItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    height: 40,
    zIndex: 2000,
  },
  pickerContainer: {
    flex: 1,
    marginLeft: 8,
    zIndex: 1,
  },
  dropDownPicker: {
    borderWidth: 0,
    backgroundColor: "transparent",
    height: 30,
    width: "100%",
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  dropDownContainer: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: theme.colors.darkLight,
    borderRadius: 20,
    maxHeight: 200,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    marginTop: 4,
  },
  dropDownText: {
    fontSize: 14,
    color: theme.colors.textDark,
  },
  dropDownItemText: {
    fontSize: 15,
    color: theme.colors.textDark,
  },
  filterPicker: {
    width: "100%",
    height: 40,
    color: theme.colors.textDark,
  },
  pickerItem: {
    fontSize: 14,
    color: theme.colors.textDark,
    backgroundColor: "white",
  },
  filterDivider: {
    width: 1,
    height: 24,
    backgroundColor: theme.colors.darkLight,
    marginHorizontal: 8,
  },
  monthGroup: {
    marginBottom: 24,
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: theme.colors.textDark,
    marginBottom: 12,
  },
  emptyStateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 32,
  },
  emptyStateText: {
    fontSize: 16,
    color: theme.colors.textLight,
    textAlign: "center",
  },
  card: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    marginBottom: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dateChip: {
    backgroundColor: theme.colors.textDark,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 16,
  },

  detailSection: {
    marginVertical: 4,
  },

  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 4,
  },

  detailLabel: {
    fontSize: 14,
    color: theme.colors.textLight,
    lineHeight: 18,
    marginTop: 2,
  },
  detailValue: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textDark,
    marginLeft: 50,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.darkLight,
    marginVertical: 4,
  },
  statusChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginTop: 8,
  },
});
